spring:
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://www.dnocm.com
          # lb: Ribbon
          # uri: lb://app-name
          predicates:
            - Path=/app/**
            - NonHeader=tt
          filters:
            # Strip first path，such base
            - StripPrefix=1
            # - RewritePath=/base/,/

        - id: jwt
          uri: lb://app-name
          predicates:
            - Path=/jwt/**
          filters:
            - CacheRequest
            - GenerateJwt=form:id,system,id
eureka:
  client:
    enabled: false
